import Axios from "axios"
import qs from 'querystring'

// Generated by https://quicktype.io

export interface Resp {
    status: string;
    count: string;
    info: string;
    infocode: string;
    tips: Tip[];
}

export interface Tip {
    id: string;
    name: string;
    district: string;
    adcode: string;
    location: string;
    address: any[] | string;
    typecode: string;
    city: any[];
}

const url = 'https://restapi.amap.com/v3/assistant/inputtips'
export default function Search(str: string, cb: (status: any, data: any) => void) {
    const payload = {
        key: "e42767b1089d44b1ad1673c23b25b850",
        keywords: str,
    }
    Axios.get<Resp>(`${url}?${qs.stringify(payload)}`, { data: payload }).then(e => cb(e.status, e.data))
}